import React, { createContext, useState, useEffect } from 'react';

// Dummy translation data - In real app, this would come from Google Translate API
const translations = {
  en: {
    'Home': 'Home',
    'Dashboard': 'Dashboard',
    'Stories': 'Stories',
    'Digital Payments': 'Digital Payments',
    'Savings': 'Savings',
    'Government Schemes': 'Government Schemes',
    'AI Coach': 'AI Coach',
    'Help': 'Help',
    'Voice Mode': 'Voice Mode',
    'Games': 'Games',
    'Namaste!': 'Namaste!',
    'Learn Money Wisdom with NoteKaka': 'Learn Money Wisdom with NoteKaka',
    'Your village guide to financial literacy. Learn about savings, budgeting, loans, and insurance in simple language.': 'Your village guide to financial literacy. Learn about savings, budgeting, loans, and insurance in simple language.',
    'Start Learning': 'Start Learning',
    'Play Games': 'Play Games',
    'Explore Without Login': 'Explore Without Login',
    'Why People Trust NoteKaka': 'Why People Trust NoteKaka',
    'Made for Villages': 'Made for Villages',
    'Content designed specifically for rural life and needs': 'Content designed specifically for rural life and needs',
    'Your Language': 'Your Language',
    'Available in Hindi, Tamil, Telugu, Bengali, Marathi and more': 'Available in Hindi, Tamil, Telugu, Bengali, Marathi and more',
    'Learn by Doing': 'Learn by Doing',
    'Interactive stories and simulations, not boring lectures': 'Interactive stories and simulations, not boring lectures',
    '100% Safe': '100% Safe',
    'No real money needed. Learn without risk': 'No real money needed. Learn without risk',
    'Success Stories from Nearby Villages': 'Success Stories from Nearby Villages',
    'Start Your Journey': 'Start Your Journey',
    'Take Financial Personality Test': 'Take Financial Personality Test',
    '5 simple questions to understand your needs': '5 simple questions to understand your needs',
    'Learn Through Stories': 'Learn Through Stories',
    'Real-life scenarios with choices and consequences': 'Real-life scenarios with choices and consequences',
    'Try Savings Simulator': 'Try Savings Simulator',
    'Practice saving without using real money': 'Practice saving without using real money',
    'Ready to Take Control of Your Money?': 'Ready to Take Control of Your Money?',
    'Join 1,50,000+ learners who are building financial confidence': 'Join 1,50,000+ learners who are building financial confidence',
    'Start Learning for Free': 'Start Learning for Free',
    'No registration required. Start immediately!': 'No registration required. Start immediately!',
    'Tips for Success': 'Tips for Success',
    'Think Before Acting': 'Think Before Acting',
    'Take time to understand each scenario. Financial decisions have consequences!': 'Take time to understand each scenario. Financial decisions have consequences!',
    'Learn from Mistakes': 'Learn from Mistakes',
    'Use each game as a learning opportunity. Try different strategies!': 'Use each game as a learning opportunity. Try different strategies!',
    'Practice Regularly': 'Practice Regularly',
    'Help your financial skills improve by playing multiple times.': 'Help your financial skills improve by playing multiple times.'
  },
  hi: {
    'Home': 'होम',
    'Dashboard': 'डैशबोर्ड',
    'Stories': 'कहानियाँ',
    'Digital Payments': 'डिजिटल भुगतान',
    'Savings': 'बचत',
    'Government Schemes': 'सरकारी योजनाएं',
    'AI Coach': 'एआई कोच',
    'Help': 'मदद',
    'Voice Mode': 'आवाज मोड',
    'Games': 'खेल',
    'Namaste!': 'नमस्ते!',
    'Learn Money Wisdom with NoteKaka': 'नोटकाका के साथ पैसे की समझ सीखें',
    'Your village guide to financial literacy. Learn about savings, budgeting, loans, and insurance in simple language.': 'आपका गाँव वित्तीय साक्षरता के लिए गाइड। बचत, बजट, ऋण और बीमा के बारे में सरल भाषा में जानें।',
    'Start Learning': 'सीखना शुरू करें',
    'Play Games': 'खेल खेलें',
    'Explore Without Login': 'बिना लॉगिन के एक्सप्लोर करें',
    'Why People Trust NoteKaka': 'लोग नोटकाका पर क्यों विश्वास करते हैं',
    'Made for Villages': 'गाँवों के लिए बनाया गया',
    'Content designed specifically for rural life and needs': 'ग्रामीण जीवन और आवश्यकताओं के लिए विशेष रूप से डिज़ाइन की गई सामग्री',
    'Your Language': 'आपकी भाषा',
    'Available in Hindi, Tamil, Telugu, Bengali, Marathi and more': 'हिंदी, तमिल, तेलुगु, बंगाली, मराठी और अन्य में उपलब्ध',
    'Learn by Doing': 'करके सीखें',
    'Interactive stories and simulations, not boring lectures': 'इंटरैक्टिव कहानियाँ और सिमुलेशन, बोरिंग व्याख्यान नहीं',
    '100% Safe': '100% सुरक्षित',
    'No real money needed. Learn without risk': 'कोई असली पैसे की जरूरत नहीं। जोखिम के बिना सीखें',
    'Success Stories from Nearby Villages': 'पास के गाँवों से सफलता की कहानियाँ',
    'Start Your Journey': 'अपनी यात्रा शुरू करें',
    'Take Financial Personality Test': 'वित्तीय व्यक्तित्व परीक्षण लें',
    '5 simple questions to understand your needs': 'आपकी जरूरतों को समझने के लिए 5 सरल सवाल',
    'Learn Through Stories': 'कहानियों के माध्यम से सीखें',
    'Real-life scenarios with choices and consequences': 'विकल्प और परिणाम के साथ वास्तविक जीवन परिदृश्य',
    'Try Savings Simulator': 'बचत सिमुलेटर आजमाएं',
    'Practice saving without using real money': 'असली पैसे का उपयोग किए बिना बचत का अभ्यास करें',
    'Ready to Take Control of Your Money?': 'अपने पैसे पर नियंत्रण लेने के लिए तैयार हैं?',
    'Join 1,50,000+ learners who are building financial confidence': '1,50,000+ शिक्षार्थियों के साथ जुड़ें जो वित्तीय आत्मविश्वास बना रहे हैं',
    'Start Learning for Free': 'मुफ्त में सीखना शुरू करें',
    'No registration required. Start immediately!': 'कोई पंजीकरण आवश्यक नहीं। तुरंत शुरू करें!',
    'Tips for Success': 'सफलता के सुझाव',
    'Think Before Acting': 'कार्य करने से पहले सोचें',
    'Take time to understand each scenario. Financial decisions have consequences!': 'प्रत्येक परिदृश्य को समझने के लिए समय लें। वित्तीय निर्णयों के परिणाम होते हैं!',
    'Learn from Mistakes': 'गलतियों से सीखें',
    'Use each game as a learning opportunity. Try different strategies!': 'प्रत्येक गेम को एक सीखने का अवसर मानें। विभिन्न रणनीतियां आजमाएं!',
    'Practice Regularly': 'नियमित रूप से अभ्यास करें',
    'Help your financial skills improve by playing multiple times.': 'कई बार खेलकर अपने वित्तीय कौशल में सुधार करें।'
  },
  ta: {
    'Home': 'முகப்பு',
    'Dashboard': 'டாஷ்போர்டு',
    'Stories': 'கதைகள்',
    'Digital Payments': 'டிஜிட்டல் பேமெண்ட்',
    'Savings': 'சேமிப்பு',
    'Government Schemes': 'அரசு திட்டங்கள்',
    'AI Coach': 'AI பயிற்சியாளர்',
    'Help': 'உதவி',
    'Voice Mode': 'குரல் முறை',
    'Games': 'விளையாட்டுகள்',
    'Namaste!': 'வணக்கம்!',
    'Learn Money Wisdom with NoteKaka': 'நோட்ககாவுடன் பண ஞானம் கற்றுக்கொள்ளுங்கள்',
    'Your village guide to financial literacy. Learn about savings, budgeting, loans, and insurance in simple language.': 'நிதி எழுத்தறிவுக்கான உங்கள் கிராம வழிகாட்டி. சேமிப்பு, பட்ജெட், கடன் மற்றும் காப்பீட்டைப் பற்றி எளிய மொழியில் அறிக.',
    'Start Learning': 'கற்றல் தொடங்கவும்',
    'Play Games': 'விளையாட்டுகளை விளையாடு',
    'Explore Without Login': 'லாகினின்றி ஆராயவும்',
    'Why People Trust NoteKaka': 'மக்கள் நோட்ககாவை ஏன் நம்புகிறார்கள்',
    'Made for Villages': 'கிராமங்களுக்கு வடிவமைக்கப்பட்டது',
    'Content designed specifically for rural life and needs': 'கிராமப்புற வாழ்க்கை மற்றும் தேவைகளுக்கு குறிப்பாக வடிவமைக்கப்பட்ட உள்ளடக்கம்',
    'Your Language': 'உங்கள் மொழி',
    'Available in Hindi, Tamil, Telugu, Bengali, Marathi and more': 'ஹிந்தி, தமிழ், తెలుగు, வங்கம், மராठி மற்றும் பல மொழிகளில் உபलब்ధம்',
    'Learn by Doing': 'செய்கையால் கற்குக',
    'Interactive stories and simulations, not boring lectures': 'ஊடாடும் கதைகள் மற்றும் சிமுலேशनો, கடினமான விரிவுரைகள் அல்ல',
    '100% Safe': '100% பாதுரக்ষணம்',
    'No real money needed. Learn without risk': 'உண்மையான பணம் தேவை இல்லை. ஆபத்து இல்லாமல் கற்குக',
    'Success Stories from Nearby Villages': 'அருகிலுள்ள கிராமங்களிலிருந்து வெற்றிக் கதைகள்',
    'Start Your Journey': 'உங்கள் முயற்சி தொடங்குங்கள்',
    'Take Financial Personality Test': 'நிதி ஆளுமை சோதனை எடுக்கவும்',
    '5 simple questions to understand your needs': 'உங்கள் தேவைகளைப் புரிந்துகொள்ள 5 எளிய கேள்விகள்',
    'Learn Through Stories': 'கதைகளின் மூலம் கற்குக',
    'Real-life scenarios with choices and consequences': 'தேர்வு மற்றும் விளைவுகளுடன் கூடிய நிஜ வாழ்க்கை சூழல்கள்',
    'Try Savings Simulator': 'சேமிப்பு சிமுலேटர்시도 செய்க',
    'Practice saving without using real money': 'உண்மையான பணத்தைப் பயன்படுத்தாமல் சேமிப்பு பயிற்சி செய்க',
    'Ready to Take Control of Your Money?': 'உங்கள் பணத்தைக் கட்டுப்பாட்டுக்குக் கொண்டு வர தயாரா?',
    'Join 1,50,000+ learners who are building financial confidence': 'நிதி நம்பிக்கையை உருவாக்கிக் கொண்டிருக்கும் 1,50,000+ கற்பவர்களுடன் சேரவும்',
    'Start Learning for Free': 'இலவசமாக கற்றல் தொடங்குங்கள்',
    'No registration required. Start immediately!': 'எந்த பதிவும் தேவை இல்லை. உடனடியாக தொடங்குங்கள்!',
    'Tips for Success': 'வெற்றியின் ஆலோசனைகள்',
    'Think Before Acting': 'செயல்பட முன் சிந்தியுங்கள்',
    'Take time to understand each scenario. Financial decisions have consequences!': 'ஒவ்வொரு சூழ்நிலையையும் புரிந்துகொள்ள நேரம் எடுத்துக் கொள்ளுங்கள். நிதி முடிவுகளுக்கு விளைவுகள் உள்ளன!',
    'Learn from Mistakes': 'பிழைகளிலிருந்து கற்குக',
    'Use each game as a learning opportunity. Try different strategies!': 'ஒவ்வொரு விளையாட்டையும் கற்றல் வாய்ப்பாக பயன்படுத்தவும். வெவ்வேறு கৌशलிகளை முயற்சி செய்யவும்!',
    'Practice Regularly': 'தொடர்ச்சியாக பயிற்சி செய்யவும்',
    'Help your financial skills improve by playing multiple times.': 'பல முறை விளையாடிப் பணி வங்கி திறமைகளை மேம்படுத்த உதவ செய்யவும்।'
  },
  te: {
    'Home': 'హోమ్',
    'Dashboard': 'డ్యాష్‌బోర్డ్',
    'Stories': 'కథలు',
    'Digital Payments': 'డిజిటల్ చెల్లింపులు',
    'Savings': 'సేవలు',
    'Government Schemes': 'ప్రభుత్వ పథకాలు',
    'AI Coach': 'AI కోచ్',
    'Help': 'సహాయం',
    'Voice Mode': 'వాయిస్ మోడ్',
    'Games': 'గేమ్‌లు',
    'Namaste!': 'నమస్కారం!',
    'Learn Money Wisdom with NoteKaka': 'నోటకాక తో డబ్బు జ్ఞానం నేర్చుకోండి',
    'Your village guide to financial literacy. Learn about savings, budgeting, loans, and insurance in simple language.': 'మీ గ్రామానికి ఆర్థిక సాక్షరత గైడ్. సేవలు, బడ్జెటు, రుణాలు మరియు బీమా గురించి సరళ భాషలో తెలుసుకోండి.',
    'Start Learning': 'నేర్చుకోవడం ప్రారంభించండి',
    'Play Games': 'గేమ్‌లు ఆడండి',
    'Explore Without Login': 'లాగిన్ లేకుండా అన్వేషించండి',
    'Why People Trust NoteKaka': 'ప్రజలు నోటకాక్‌కు ఎందుకు విశ్వాసం చేస్తారు',
    'Made for Villages': 'గ్రామాల కోసం తయారుచేసిన',
    'Content designed specifically for rural life and needs': 'గ్రామీణ జీవితం మరియు అవసరాల కోసం ప్రత్యేకంగా రూపొందించిన కంటెంట్',
    'Your Language': 'మీ భాష',
    'Available in Hindi, Tamil, Telugu, Bengali, Marathi and more': 'హిందీ, తమిళం, తెలుగు, బెంగాలీ, మరాఠీ మరియు మరిన్నింటిలో లభ్యమైనవి',
    'Learn by Doing': 'చేయడం ద్వారా నేర్చుకోండి',
    'Interactive stories and simulations, not boring lectures': 'ఇంటరాక్టివ్ కథలు మరియు సిమ్యులేషన్‌లు, నీరసగా ఉండే ఉపన్యాసాలు కాదు',
    '100% Safe': '100% సురక్షితం',
    'No real money needed. Learn without risk': 'నిజమైన డబ్బు అవసరం లేదు. ఎటువంటి ప్రమాదం లేకుండా నేర్చుకోండి',
    'Success Stories from Nearby Villages': 'సమీప గ్రామాల నుండి విజయ కథలు',
    'Start Your Journey': 'మీ ప్రయాణం ప్రారంభించండి',
    'Take Financial Personality Test': 'ఆర్థిక ఆభిరుచి పరీక్ష తీసుకోండి',
    '5 simple questions to understand your needs': 'మీ అవసరాలను అర్థం చేసుకోవటానికి 5 సాధారణ ప్రశ్నలు',
    'Learn Through Stories': 'కథల ద్వారా నేర్చుకోండి',
    'Real-life scenarios with choices and consequences': 'ఎంపికలు మరియు పర్యవసానాలతో నిజ జీవితం యొక్క దృశ్యాలు',
    'Try Savings Simulator': 'సేవల సిమ్యులేటర్‌ని ప్రయత్నించండి',
    'Practice saving without using real money': 'నిజమైన డబ్బు ఉపయోగించకుండా సేవ ఆచరణ చేయండి',
    'Ready to Take Control of Your Money?': 'మీ డబ్బు నియంత్రణ తీసుకోవటానికి సిద్ధమైనారా?',
    'Join 1,50,000+ learners who are building financial confidence': 'ఆర్థిక విశ్వాసాన్ని నిర్మిస్తున్న 1,50,000+ నిపుణులతో చేరండి',
    'Start Learning for Free': 'ఉచితంగా నేర్చుకోవడం ప్రారంభించండి',
    'No registration required. Start immediately!': 'ఎటువంటి నమోదు అవసరం లేదు. వెంటనే ప్రారంభించండి!',
    'Tips for Success': 'విజయం కోసం చిట్కాలు',
    'Think Before Acting': 'చర్య తీసుకోకముందు ఆలోచించండి',
    'Take time to understand each scenario. Financial decisions have consequences!': 'ప్రతిটి దృశ్యాన్ని అర్థం చేసుకోవటానికి సమయం తీసుకోండి. ఆర్థిక నిర్ణయాలకు పర్యవసానాలు ఉన్నాయి!',
    'Learn from Mistakes': 'తప్పుల నుండి నేర్చుకోండి',
    'Use each game as a learning opportunity. Try different strategies!': 'ప్రతిটి గేమ్‌ను శిక్షణ అవకాశంగా ఉపయోగించండి. వివిధ వ్యూహాలను ప్రయత్నించండి!',
    'Practice Regularly': 'క్రమం తప్పక ఆచరణ చేయండి',
    'Help your financial skills improve by playing multiple times.': 'అనేక సార్లు ఆడటం ద్వారా మీ ఆర్థిక నైపుణ్యాలను మెరుగుపరచుకోండి.'
  },
  bn: {
    'Home': 'হোম',
    'Dashboard': 'ড্যাশবোর্ড',
    'Stories': 'গল্প',
    'Digital Payments': 'ডিজিটাল পেমেন্ট',
    'Savings': 'সঞ্চয়',
    'Government Schemes': 'সরকারি স্কিম',
    'AI Coach': 'এআই কোচ',
    'Help': 'সাহায্য',
    'Voice Mode': 'ভয়েস মোড',
    'Games': 'গেম',
    'Namaste!': 'নমস্কার!',
    'Learn Money Wisdom with NoteKaka': 'নোটকাকার সাথে অর্থ জ্ঞান শিখুন',
    'Your village guide to financial literacy. Learn about savings, budgeting, loans, and insurance in simple language.': 'আপনার গ্রামের আর্থিক সাক্ষরতার গাইড। সঞ্চয়, বাজেটিং, ঋণ এবং বীমা সম্পর্কে সহজ ভাষায় শিখুন।',
    'Start Learning': 'শিখতে শুরু করুন',
    'Play Games': 'গেম খেলুন',
    'Explore Without Login': 'লগইন ছাড়াই এক্সপ্লোর করুন',
    'Why People Trust NoteKaka': 'মানুষ কেন নোটকাকাকে বিশ্বাস করে',
    'Made for Villages': 'গ্রামের জন্য তৈরি',
    'Content designed specifically for rural life and needs': 'গ্রামীণ জীবন এবং চাহিদার জন্য বিশেষভাবে ডিজাইন করা সামগ্রী',
    'Your Language': 'আপনার ভাষা',
    'Available in Hindi, Tamil, Telugu, Bengali, Marathi and more': 'হিন্দি, তামিল, তেলুগু, বাংলা, মারাঠি এবং আরও অনেক ভাষায় উপলব্ধ',
    'Learn by Doing': 'করে করে শিখুন',
    'Interactive stories and simulations, not boring lectures': 'ইন্টারঅ্যাক্টিভ গল্প এবং সিমুলেশন, বিরক্তিকর বক্তৃতা নয়',
    '100% Safe': '100% সুরক্ষিত',
    'No real money needed. Learn without risk': 'প্রকৃত অর্থের প্রয়োজন নেই। ঝুঁকি ছাড়াই শিখুন',
    'Success Stories from Nearby Villages': 'কাছাকাছি গ্রাম থেকে সাফল্যের গল্প',
    'Start Your Journey': 'আপনার যাত্রা শুরু করুন',
    'Take Financial Personality Test': 'আর্থিক ব্যক্তিত্ব পরীক্ষা নিন',
    '5 simple questions to understand your needs': 'আপনার চাহিদা বুঝতে 5টি সহজ প্রশ্ন',
    'Learn Through Stories': 'গল্পের মাধ্যমে শিখুন',
    'Real-life scenarios with choices and consequences': 'পছন্দ এবং ফলাফল সহ বাস্তব জীবনের পরিস্থিতি',
    'Try Savings Simulator': 'সঞ্চয় সিমুলেটর চেষ্টা করুন',
    'Practice saving without using real money': 'প্রকৃত অর্থ ব্যবহার না করে সঞ্চয়ের অভ্যাস করুন',
    'Ready to Take Control of Your Money?': 'আপনার অর্থ নিয়ন্ত্রণ নিতে প্রস্তুত?',
    'Join 1,50,000+ learners who are building financial confidence': 'আর্থিক আত্মবিশ্বাস তৈরি করছেন এমন 1,50,000+ শিক্ষার্থীদের সাথে যোগ দিন',
    'Start Learning for Free': 'বিনামূল্যে শিখতে শুরু করুন',
    'No registration required. Start immediately!': 'কোন নিবন্ধনের প্রয়োজন নেই। এখনই শুরু করুন!',
    'Tips for Success': 'সাফল্যের টিপস',
    'Think Before Acting': 'কাজ করার আগে চিন্তা করুন',
    'Take time to understand each scenario. Financial decisions have consequences!': 'প্রতিটি পরিস্থিতি বুঝতে সময় নিন। আর্থিক সিদ্ধান্তের পরিণতি আছে!',
    'Learn from Mistakes': 'ভুল থেকে শিখুন',
    'Use each game as a learning opportunity. Try different strategies!': 'প্রতিটি গেমকে শেখার সুযোগ হিসাবে ব্যবহার করুন। বিভিন্ন কৌশল চেষ্টা করুন!',
    'Practice Regularly': 'নিয়মিত অনুশীলন করুন',
    'Help your financial skills improve by playing multiple times.': 'একাধিকবার খেলে আপনার আর্থিক দক্ষতা উন্নত করুন।'
  },
  mr: {
    'Home': 'होम',
    'Dashboard': 'डॅशबोर्ड',
    'Stories': 'कथा',
    'Digital Payments': 'डिजिटल पेमेंट',
    'Savings': 'बचत',
    'Government Schemes': 'सरकारी योजना',
    'AI Coach': 'एआई कोच',
    'Help': 'मदत',
    'Voice Mode': 'व्हॉइस मोड',
    'Games': 'खेळ',
    'Namaste!': 'नमस्कार!',
    'Learn Money Wisdom with NoteKaka': 'नोटकाकाच्या साथ पैसे विषयी ज्ञान शिका',
    'Your village guide to financial literacy. Learn about savings, budgeting, loans, and insurance in simple language.': 'आपल्या गावाचा आर्थिक साक्षरतेचा मार्गदर्शक. बचत, बजेटिंग, कर्ज आणि विमा विषयी सोप्या भाषेत शिका.',
    'Start Learning': 'शिकण्यास सुरुवात करा',
    'Play Games': 'खेळ खेळा',
    'Explore Without Login': 'लॉगिन शिवाय एक्सप्लोर करा',
    'Why People Trust NoteKaka': 'लोक नोटकाकावर का विश्वास करतात',
    'Made for Villages': 'गावांसाठी बनवले गेले',
    'Content designed specifically for rural life and needs': 'ग्रामीण जीवन आणि गरजांसाठी विशेषतः डिজाइन केलेले सामग्री',
    'Your Language': 'आपली भाषा',
    'Available in Hindi, Tamil, Telugu, Bengali, Marathi and more': 'हिंदी, तमिळ, तेलुगु, बंगाली, मराठी आणि बरेच काही मध्ये उपलब्ध',
    'Learn by Doing': 'केल्याने शिका',
    'Interactive stories and simulations, not boring lectures': 'इंटरएक्टिव्ह कथा आणि सिम्युलेशन, कंटाळवाणे व्याख्यान नाहीत',
    '100% Safe': '100% सुरक्षित',
    'No real money needed. Learn without risk': 'खरे पैसे लागत नाहीत. जोखीम शिवाय शिका',
    'Success Stories from Nearby Villages': 'जवळपासच्या गावांतून यशाच्या कथा',
    'Start Your Journey': 'आपली यात्रा सुरु करा',
    'Take Financial Personality Test': 'आर्थिक व्यक्तिमत्व चाचणी घ्या',
    '5 simple questions to understand your needs': 'आपल्या गरजा समजून घेण्यासाठी 5 साधे प्रश्न',
    'Learn Through Stories': 'कथांद्वारे शिका',
    'Real-life scenarios with choices and consequences': 'निवड आणि परिणामांसह वास्तविक जीवनातील परिस्थिती',
    'Try Savings Simulator': 'बचत सिम्युलेटर वापरून पहा',
    'Practice saving without using real money': 'खरे पैसे वापरून बचत करण्याची सराव करा',
    'Ready to Take Control of Your Money?': 'आपल्या पैशांचे नियंत्रण घेण्यास तयार आहात?',
    'Join 1,50,000+ learners who are building financial confidence': 'आर्थिक आत्मविश्वास तयार करणार्या 1,50,000+ शिक्षार्थ्यांसह सामील व्हा',
    'Start Learning for Free': 'विनामूल्य शिकण्यास सुरुवात करा',
    'No registration required. Start immediately!': 'कोणत्याही नोंदणीची आवश्यकता नाही. लगेच सुरुवात करा!',
    'Tips for Success': 'यशाचे टिप्स',
    'Think Before Acting': 'कारवाई करण्यापूर्वी विचार करा',
    'Take time to understand each scenario. Financial decisions have consequences!': 'प्रत्येक परिस्थिती समजून घेण्यास वेळ घ्या. आर्थिक निर्णयांचे परिणाम आहेत!',
    'Learn from Mistakes': 'चुकांमधून शिका',
    'Use each game as a learning opportunity. Try different strategies!': 'प्रत्येक खेळाचा शिक्षणाचा संधी म्हणून उपयोग करा. विविध धोरणे वापरून पहा!',
    'Practice Regularly': 'नियमितपणे सराव करा',
    'Help your financial skills improve by playing multiple times.': 'अनेक वेळा खेळून आपल्या आर्थिक कौशल्य सुधारण्यात मदत करा.'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');
  const [availableLanguages, setAvailableLanguages] = useState([
    { code: 'en', name: 'English', nativeName: 'English' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी' }
  ]);

  const translate = (text) => {
    if (currentLanguage === 'en') return text;
    return translations[currentLanguage]?.[text] || text;
  };

  const changeLanguage = (langCode) => {
    setCurrentLanguage(langCode);
    localStorage.setItem('preferredLanguage', langCode);
  };

  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage');
    if (savedLanguage && availableLanguages.find(lang => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      availableLanguages,
      translate,
      changeLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { LanguageContext };